issuer: Global Security
keywords:
- 'globalsecurity.co.nz'

fields:
  invoice_number: '[Ii]nvoice\s*[Nn][Oo]?\s*\:?\s*(\w+)'
  bc_number: '(?<!C\/\-)\sB[oO]?[Dd]?[Yy]?\s*[Cc][oO]?[Rr]?[Pp]?[Oo]?[Rr]?[Aa]?[Tt]?[Ee]?\s*[Aa]?[Dd]?[Mm]?[Ii]?[ni]?[Ss]?[Tt]?[Rr]?[Aa]?[Tt]?[Ii]?[Oo]?[Nn]?\s*[Bb]?[Cc]? *(\d+)\s(?!\s*Ltd)'
  gst_number: 'GST\s*[Nn]?[Oo]?.*\s*[^\d](\d{2,3}\-\d{3}\-\d{3})\s'
  date: 'D[Aa][Tt][Ee].*[^\d](\d{1,2}[^\d]+\w{3,9}[^\d]+20\d\d)[^\d]'
  due_date: 'Due\s*Date.*[^\d](\d{1,2}[^\d]+\d{1,2}[^\d]+20\d\d)[^\d]'
  amount: 'Amount\s*Due.*\s\$?([\d\,]{1,10}\.[\d]{2})'
  gst: '15%'

options:
  currency: NZD
  remove_whitespace: false
  date_formats:
    - '%d-%b-%y'
    - '%d-%m-%y'
    - '%d.%m.%Y'
    - '%B %d'
    - '%b %d, %Y'
    - '%d %b %Y'
    - '%d %b %y'
    - '%d/%m/%Y'
    - '%d/%m/%y'
    - '%d/%M/%y'
    - '%d-%b-%Y'


